# 神經網路計算(二)
## 小批次學習
* 輸入層一次輸入多筆訓練資料，多筆訓練資料整批(同時)由神經網路進行計算 

參考: Deep Learning, 齋藤康毅，OREILLY

In [3]:
import numpy as np

## Activation functions
### Sigmoid函數

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [5]:
X=np.array([[1.0, 0.5], [1.0, 1.5], [0.7, 0.9]])

In [6]:
sigmoid(X)

array([[0.73105858, 0.62245933],
       [0.73105858, 0.81757448],
       [0.66818777, 0.7109495 ]])

### ReLU函數

In [7]:
def relu(x):
    return np.maximum(0, x)

In [8]:
X=np.array([[1.0, 0.5], [-1.0, 1.5], [0.7, -0.9]])

In [9]:
relu(X)

array([[1. , 0.5],
       [0. , 1.5],
       [0.7, 0. ]])

### Softmax函數

In [10]:
def softmax_0(x):
    c=np.max(x)
    x = x - c
    return np.exp(x) / np.sum(np.exp(x))

In [11]:
def softmax(x):
    x = x - np.max(x, axis=-1, keepdims=True)
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

In [12]:
x=np.array([[1.0, 0.5], [1.0, 1.5], [0.7, 0.9]])

In [13]:
np.max(x)

1.5

In [14]:
np.max(x, axis=-1, keepdims=True)

array([[1. ],
       [1.5],
       [0.9]])

In [15]:
x - np.max(x, axis=-1, keepdims=True)

array([[ 0. , -0.5],
       [-0.5,  0. ],
       [-0.2,  0. ]])

In [16]:
x = x - np.max(x, axis=-1, keepdims=True)
np.exp(x)

array([[1.        , 0.60653066],
       [0.60653066, 1.        ],
       [0.81873075, 1.        ]])

In [17]:
np.sum(np.exp(x), axis=-1, keepdims=True)

array([[1.60653066],
       [1.60653066],
       [1.81873075]])

In [18]:
softmax(x)

array([[0.62245933, 0.37754067],
       [0.37754067, 0.62245933],
       [0.450166  , 0.549834  ]])

In [19]:
softmax_0(x) # 這是錯誤的!

array([[0.19873635, 0.12053969],
       [0.12053969, 0.19873635],
       [0.16271156, 0.19873635]])

## Loss fnctions
### Cross entropy error (交叉熵誤差)

In [20]:
def cross_entropy_error_0(y, t):
    return -np.sum(t * np.log(y + 1e-7))

In [21]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
        
    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

In [22]:
y=np.array([[0.9, 0.2], [0.6, 0.4], [0.7, 0.3]])
t=np.array([[1, 0], [0, 1], [1, 0]])

In [23]:
np.log(y + 1e-7)

array([[-0.1053604 , -1.60943741],
       [-0.51082546, -0.91629048],
       [-0.3566748 , -1.20397247]])

In [24]:
t * np.log(y + 1e-7)

array([[-0.1053604 , -0.        ],
       [-0.        , -0.91629048],
       [-0.3566748 , -0.        ]])

In [25]:
np.sum(t * np.log(y + 1e-7))

-1.3783256875025076

In [26]:
cross_entropy_error(y, t)

0.4594418958341692

In [27]:
cross_entropy_error_0(y, t)

1.3783256875025076

## 多層神經網路小批次學習
* 輸入層一次輸入多筆訓練資料，多筆訓練資料整批(同時)由神經網路進行計算

#### 輸入層

In [60]:
X=np.array([1.0, 0.5, 2, 1.2, 2.5, 0.7])
t=np.array([0,0,1,0])

In [29]:
X.shape

(6,)

In [30]:
X

array([1. , 0.5, 2. , 1.2, 2.5, 0.7])

#### 第一層

In [31]:
W1=np.array([[0.1, 0.3, 0.5, 0.4, 0.2], [0.2, 0.4, 0.6, 0.1, 0.7], [0.6, 0.1, 0.7, 0.2, 0.4], [0.2, 0.1, 0.6, 0.4, 0.8], [0.5, 0.3, 0.6, 0.1, 0.2], [0.9, 0.2, 0.7, 0.3, 0.4]])
B1=np.array([0.1, 0.2, 0.3, 0.4, 0.5])

In [32]:
print(X.shape)
print(W1.shape)
print(B1.shape)

(6,)
(6, 5)
(5,)


In [33]:
A1=np.dot(X, W1)+B1
print(A1)

[3.62 1.91 5.21 2.19 3.59]


In [34]:
Z1=relu(A1)
print(Z1)

[3.62 1.91 5.21 2.19 3.59]


#### 第二層

In [35]:
W2=np.array([[0.3, 0.5, 0.4, 0.2], [0.2, 0.4, 0.6, 0.7], [0.6, 0.1, 0.7, 0.2], [0.1, 0.6, 0.4, 0.8], [0.9, 0.2, 0.5, 0.7]])
B2=np.array([0.1, 0.2, 0.3, 0.4])

In [36]:
print(Z1.shape)
print(W2.shape)
print(B2.shape)

(5,)
(5, 4)
(4,)


In [37]:
A2=np.dot(Z1, W2)+B2
print(A2)

[8.144 5.327 9.212 7.768]


In [38]:
Z2=relu(A2)
print(Z2)

[8.144 5.327 9.212 7.768]


#### 第三層

In [39]:
W3=np.array([[0.1, 0.7, 0.4, 0.8], [0.2, 0.4, 0.2, 0.7], [0.3, 0.5, 0.3, 0.2], [0.1, 0.1, 0.7, 0.2]])
B3=np.array([0.1, 0.2, 0.3, 0.4])

In [40]:
print(Z2.shape)
print(W3.shape)
print(B3.shape)

(4,)
(4, 4)
(4,)


In [41]:
A3=np.dot(Z2, W3)+B3
print(A3)

[ 5.5202 13.4144 12.8242 14.0401]


In [47]:
Z3=sigmoid(A3)
print(Z3)

[0.99601093 0.99999851 0.99999731 0.9999992 ]


In [48]:
#第四層(輸出層)

In [49]:
W4=np.array([[0.5, 0.5, 0.3, 0.2], [0.7, 0.1, 0.8, 0.4], [0.4, 0.2, 0.6, 0.3], [0.2, 0.3, 0.4, 0.5]])
B4=np.array([0.1, 0.2, 0.3, 0.4])

In [50]:
print(Z3.shape)
print(W4.shape)
print(B4.shape)

(4,)
(4, 4)
(4,)


In [51]:
A4=np.dot(Z3, W4)+B4
print(A4)

[1.89800318 1.29800454 2.39880015 1.79920038]


In [81]:
y=softmax(A4)
print(y)

[0.24361904 0.13370114 0.40198013 0.22069969]


In [82]:
y.shape #一個批次至少四筆訓練資料

(4,)

### Cross entropy error (交叉熵誤差)

In [97]:
t=np.array([0,0,1,0])

In [98]:
print(t)

[0 0 1 0]


In [99]:
print(y)

[0.24361904 0.13370114 0.40198013 0.22069969]


In [101]:
cross_entropy_error(y, t)

0.9113523721605344